economist-components/provision-react-component

assets/build.sh
This fixes an issue with npm which cowardly refuses to build
in working directories that don\'t match the name of the
package. See this piece of code:
https://github.com/npm/npm/blob/94929cf05854886b1aa9b611ad3bbb6dbbb575f3/lib/utils/lifecycle.js#L54-L62'
=> fix(build): set unsafe-perm to true

package.json, src/provision-stylelint-config-strict.js
semantic-release will exit with non-zero exit codes if there is no new
version to release, as such, any `chore`/`style`/`doc` only commits will
fail the build. This change makes it so that the exit code semantic
release emits is ignored, and the build will pass, even if it fails.
=> fix(build): ignore semantic-release errors

src/provision-docgen.js
Also according to postcss-cli docs it should be `postcss [options] -o output/file.css input/file.css` so switch order to reflect.
=> fix: doc:css script running on lib when it should be src

assets/build.sh
This change seems impactful, but it's not really.
Traditionally, components using the old devpack were using `economistprod/node4-base` ([see here](
https://github.com/EconomistDigitalSolutions/fe-component-devpack/blob/master/build.sh#L4)).
This is an old, no longer maintained image. During the development of provision-react it was
decided to migrate to the official fe-blogs image, however, the differences between the two are
very large, as `economistprod/node4-base` is Debian based and the fe-blogs image is Alpine based.
This effectively reverts the switch to the fe-blogs image, back to a Debian based build container.
It is important we do this because Alpine uses lib musl as its core std lib, and our test tooling -
specifically sauceconnect (part of our Karma suite) relies on glibc …
=> fix(build): switch to node:argon-slim docker image

assets/build.sh
git is needed for semantic-release and pages scripts
=> fix(build): ensure git is installed

assets/build.sh
node:argon-slim is missing too many tools to build the test environment needed for our components.
It is missing git (required by build), python (used for node-gyp, required by devdeps), and will not successfully install phantomjs (required in our karma setup). node:argon has all of these.
Drawing this to @fabiosantoscode's attention has they originally objected to using `node:argon` over `node:argon-slim`.
=> fix(build): use node:argon over node:argon-slim

src/provision-packagejson.js
https is the canonical url for all github links - it redirects http to https,
so we should link directly to https to save a redirect
@fabiosantoscode
=> fix(provision-packagejson): switch http github links to https

src/provision-mainfiles.js
This adds the babel-polyfill to the example.js, just in case any non-polyfilled code is used within the example.
=> fix(provision-mainfiles): import babel-polyfill in example template

assets/build.sh
This tries to install against sinopia twice, then flips the table and uses the real registry.
This means that we get the speed of a cached sinopia-driven install, but if that fails then we can have a slow one.
=> feat: Do some retries on NPM

assets/build.sh
This makes our builds avoid using sinopia for the `@semantic-release` repository.
=> fix: set the @semantic-release registry to registry.npmjs.com

src/provision-legacy-removal.js
I noticed that we have a few more dangling dependencies - so part of this PR removes them while provisioning - as part of the `provision-legacy-removal` script.
This PR also removes the `pre-commit` package.json config, as we're now using `ghooks`. This has caused some conflicts before as having the two of them doesn't work so well. I think @gcedo experienced this issue before a few times. This should fix that now :smile: 
Lastly, I was using `lodash.without` wrong, and so I've fixed that so that it actually removes file references from package.json
=> Legacy removal fixes

package-versions.json, src/provision-legacy-removal.js
We have already from babel-runtime to polyfill (#40) - but some reprovisioned
components have been left with the runtime option. This commit removes the
runtime option if present, ensuring that the polyfill is the only thing used
=> Drop babel runtime

src/provision-legacy-removal.js
These are no longer executed from within the scripts object and so are just cruft
=> feat(provision-legacy-removal): remove npm-watch and watch config

assets/build.sh
Sinopia seems to mess with npm publish settings. This change removes the sinopia
registry settings after install - so that it is not used come publish time. We
only use sinopia to cache npm dependencies, so this should not impact the build
(except for fixing sinopia publish breakages)
=> fix(build): remove registry config post-install

src/provision-react-testsuite.js
The tests need to import from src, to make the watch process more reliable.
=> fix: ensure tests import code from `src` not `lib`

src/index.js
I misdiagnosed the problem before—it wasn't the missing `.git`, which indeed does not matter, but the misplaced colon that fouled things up.
=> Correct github path

src/provision-react-testsuite.js
Enables the element to be correctly found.
=> fix: prefixed classname with . rendered.find()

package.json
We pinned this because of babel-eslint and es-traverse failing, but it does not any more. Lets switch back.
=> chore: switch eslint pin to semver major (^)

assets/karma.conf.js
If we don't specify the platform, SauceLabs has a tendency to prefer Windows, and
so we are testing Safari 5 on windows, which was discontinued in 2012. This change
specifies a modern OSX platform, which will make it use a modern safari (Safari 7).
Safari 7/Mavericks was chosen as it is the oldest OSX with > 10% adoption, according
to https://www.gosquared.com/global/mac/el-capitan/#launch
=> fix(karma): ensure we test on a modern Safari

src/index.js, src/provision-legacy-removal.js
This change removes lines that are potentially already existing in old components we have.
These old lines cause lots of problems because they're incompatible with the new version -
such as `*.js`.
=> fix: remove legacy gitignore lines

src/provision-travis.js
This fixes the broken travis deployment scripts - which would always fail because npm run pages
would deploy to an http url which it had no access to. This specifies the repository option which
includes a GH_TOKEN so that travis can push. It also reorders the script to ensure semantic-release
is always run first, as this is the higher priority of the two publish scripts
=> fix(travis): fix broken deployments by ensuring GH_TOKEN repo url

src/provision-docgen.js, src/provision-legacy-removal.js
The browserify.transform field is read by upstream dependencies during the browserify compilation phase, which was highlighted
due to the babel 5-6 transition. We already compile down the ES6 code into ES5 code during the prepublish step, so at-best the
browserify transform field is slowing down our upstream builds, and at worst it is breaking them.
This commit removes the browserify.transform field, in favour of adding `-t babelify` to the doc build step - which is the only
place that makes use of browserify in these builds. This means upstream builds just pull in plain lib/index and do not pass it
through any transforms
=> fix(docgen): move browserify transform into command line flags
